---
- name: Deploy Redmine application
  hosts: webservers
  become: yes
  vars:
    redmine_env_path: .env
  tasks:
    - name: Copy .env file for Redmine
      ansible.builtin.template:
        src: redmine.env.j2
        dest: "{{ redmine_env_path }}"
        mode: '0644'

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports:
          - "3000:3000"
        env_file: "{{ redmine_env_path }}"
      become: yes
  tags:
    - redmine

  roles:
    - datadog.datadog
  tags:
    - datadog
